import type {CSSProperties} from "react";

interface filterStyles {
  container: CSSProperties,
  searchBox: CSSProperties,
  input: CSSProperties,
  searchButton: CSSProperties,
  searchIcon: CSSProperties,
  params: CSSProperties,
  paramGroup: CSSProperties,
  label: CSSProperties,
  checkboxGroup: CSSProperties,
  checkbox: CSSProperties,
  select: CSSProperties,
  buttonBox: CSSProperties,
  resetButton: CSSProperties,
  priceBox: CSSProperties,
  pillGroup: CSSProperties,
  pill: CSSProperties,
  priceGroup: CSSProperties,
  priceInput: CSSProperties,
  dropdown: CSSProperties,
  dropdownList: CSSProperties,
  dropdownItem: CSSProperties,
  dropdownWrapper: CSSProperties,
  dropdownButton: CSSProperties,

  sortBox: CSSProperties,
  sortSelect: CSSProperties,
  sortOption: CSSProperties,

  modalSearch: CSSProperties,
  modalSearchBox: CSSProperties,
  modalSearchInput: CSSProperties,
  modalText: CSSProperties,
}

export default function filtersGetStyle(isDarkmode: boolean): filterStyles {
  const colors = {
    lightBg: "#f9f9fb",
    darkBg: "#1c1c24",
    lightText: "#2d2d2d",
    darkText: "#f5f5f5",
    accent: "#4a90e2",
    accentHover: "#357ABD",
    borderLight: "#d0d0d5",
    borderDark: "#444",
    danger: "#e74c3c",
  };

  const baseBg = isDarkmode ? colors.darkBg : colors.lightBg;
  const baseText = isDarkmode ? colors.darkText : colors.lightText;
  const borderColor = isDarkmode ? colors.borderDark : colors.borderLight;

  return {
    container: {
      width: "100%",
      maxWidth: "1000px",
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
      background: baseBg,
      color: baseText,
      padding: "2rem",
      borderRadius: "12px",
      boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
      fontFamily: "'Inter','Segoe UI',sans-serif",
      boxSizing: "border-box",
    },

    searchBox: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      height: "2.75rem",
      gap: "0.5rem",
    },
    input: {
      flex: 1,
      padding: "0.5rem 0.75rem",
      border: `1px solid ${borderColor}`,
      borderRadius: "8px",
      background: isDarkmode ? "#2a2a33" : "#fff",
      color: baseText,
      fontSize: "0.95rem",
      transition: "border-color 0.2s ease",
    },
    searchButton: {
      width: "2.75rem",
      height: "2.75rem",
      border: "none",
      borderRadius: "8px",
      background: colors.accent,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "background 0.2s ease",
    },
    searchIcon: {
      aspectRatio: "1/1",
      height: "60%",
      filter: isDarkmode ? "invert(1)" : "none",
    },
    params: {
      display: "flex",
      justifyContent: 'space-between',
      flexWrap: "wrap",
      gap: "2rem",
    },
    paramGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      minWidth: "150px",
    },
    label: {
      fontWeight: 600,
      fontSize: "0.9rem",
      marginBottom: "0.25rem",
    },
    checkboxGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "0.4rem",
    },
    checkbox: {
      width: "18px",
      height: "18px",
      accentColor: colors.accent,
      cursor: "pointer",
    },
    buttonBox: {
      display: "flex",
      justifyContent: "flex-end",
      alignSelf: 'flex-end',
      alignItems: 'flex-end'
    },
    resetButton: {
      padding: "0.5rem 1rem",
      border: "none",
      borderRadius: "8px",
      background: colors.danger,
      color: "#fff",
      cursor: "pointer",
      fontWeight: 600,
      transition: "background 0.2s ease",
    },
    pillGroup: {
      display: "flex",
      gap: "0.5rem",
    },
    pill: {
      padding: "0.4rem 0.8rem",
      borderRadius: "999px",
      border: `1px solid ${borderColor}`,
      background: isDarkmode ? "#333" : "#f0f0f0",
      color: baseText,
      cursor: "pointer",
      fontSize: "0.9rem",
      userSelect: "none",
      transition: "background 0.2s ease, color 0.2s ease",
    },
    priceBox: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      minWidth: "120px",
    },
    priceGroup: {
      display: "flex",
      gap: "0.5rem",
    },
    priceInput: {
      width: "70px",
      padding: "0.3rem 0.5rem",
      border: `1px solid ${borderColor}`,
      borderRadius: "6px",
      background: isDarkmode ? "#2a2a33" : "#fff",
      color: baseText,
      fontSize: "0.85rem",
      textAlign: "center",
      transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    },
    select: {
      padding: "0.4rem 0.6rem",
      border: `1px solid ${borderColor}`,
      borderRadius: "6px",
      background: isDarkmode ? "#2a2a33" : "#fff",
      color: baseText,
      fontSize: "0.9rem",
      cursor: "pointer",
      transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    },
    dropdown: {
      border: `1px solid ${borderColor}`,
      borderRadius: "6px",
      background: isDarkmode ? "#2a2a33" : "#fff",
      color: baseText,
      fontSize: "0.9rem",
      cursor: "pointer",
      padding: "0.4rem 0.6rem",
    },
    dropdownWrapper: {
      position: "relative",
      display: "inline-block",
    },
    dropdownButton: {
      padding: "0.4rem 0.6rem",
      border: `1px solid ${borderColor}`,
      borderRadius: "6px",
      width: "100%",
      background: isDarkmode ? "#2a2a33" : "#fff",
      color: baseText,
      fontSize: "0.9rem",
      cursor: "pointer",
      textAlign: "left",
    },
    dropdownList: {
      position: "absolute",
      top: "100%",
      left: 0,
      right: 0,
      margin: 0,
      padding: "0.5rem 0",
      listStyle: "none",
      background: isDarkmode ? "#2a2a33" : "#fff",
      border: `1px solid ${borderColor}`,
      borderRadius: "6px",
      boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
      maxHeight: 0,
      overflow: "hidden",
      transition: "max-height 0.3s ease",
      zIndex: 5,
    },
    dropdownItem: {
      padding: "0.25rem 0.5rem",
      cursor: "pointer",
      width: "100%",
      textAlign: "left",
      transition: "background 0.2s ease",
    },
    modalSearch: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      background: isDarkmode ? "rgba(0,0,0,0.7)" : "rgba(0,0,0,0.5)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1000,
      opacity: 0,
      pointerEvents: "none",
      transition: "opacity 0.35s ease",
      fontFamily: "'Inter','Segoe UI',sans-serif",
    },
    modalSearchBox: {
      background: baseBg,
      padding: "2rem",
      borderRadius: "16px",
      boxShadow: "0 12px 32px rgba(0,0,0,0.35)",
      display: "flex",
      flexDirection: "column",
      gap: "1.25rem",
      width: "90%",
      maxWidth: "700px",
      transition: "transform 0.35s ease, opacity 0.35s ease",
    },
    modalSearchInput: {
      width: "100%",
      boxSizing: "border-box",
      padding: "0.85rem 1rem",
      borderRadius: "10px",
      border: `1px solid ${borderColor}`,
      background: isDarkmode ? "#2a2a33" : "#f9f9fb",
      color: baseText,
      fontSize: "1rem",
      outline: "none",
      transition: "border-color 0.25s ease, box-shadow 0.25s ease",
    },

    modalText: {
      fontSize: "1.1rem",
      fontWeight: 600,
      color: baseText,
      textAlign: "center",
    },
    sortBox: {
      display: "flex",
      gap: "1rem",
      justifyContent: "space-between",
    },
    sortSelect: {
      padding: "0.4rem 0.6rem",
      border: `1px solid ${borderColor}`,
      borderRadius: "6px",
      background: baseBg,
      color: baseText,
      fontSize: "0.9rem",
      cursor: "pointer",
      transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    },
    sortOption: {
      background: baseBg,
      color: baseText,
      fontSize: "0.9rem",
    },
  };
}
